name: AuthAnvilLogin
version: '1.2.5-Stable'
main: net.chen.ll.authAnvilLogin.AuthAnvilLogin
api-version: '1.19'
load: POSTWORLD
authors: [ Chen ]
support-folia: true
depend:
  - AuthMe
  - ProtocolLib
softdepend:
  - PlaceholderAPI
  - floodgate
description: Use anvil to login
website: i.whocare.life
commands:
  anvillogin:
    description: Open anvil login gui
    usage: /anvillogin
    aliases:
      - al
      - avl
    permission-message: &cYou don't have permission to use this command!

