name: AuthAnvilLogin
version: '2.2.1-Stable'
main: net.chen.ll.authAnvilLogin.AuthAnvilLogin
api-version: '1.12'
load: POSTWORLD
authors: [ Chen ]
folia-supported: true
depend:
  - AuthMe
softdepend:
  - PlaceholderAPI
  - floodgate
description: Use anvil to login
website: i.whocare.life
commands:
  anvillogin:
    description: Open anvil login gui
    usage: /anvillogin
    aliases:
      - al
      - avl
    permission-message: &cYou don't have permission to use this command!

